Remove JFrog downtime notice
jenkinsci/.github pull request #108
Opened 2022-12-19 15:13 UTC by NotMyFault

2022-12-19 15:16 UTC, lemeurherve requested changes
LGTM, need to remove 2 more lines though

2022-12-19 15:16 UTC, lemeurherve commented on profile/README.md
```suggestion
```

2022-12-19 15:16 UTC, NotMyFault commented on profile/README.md
>  ##
```suggestion
```

2022-12-19 15:17 UTC, lemeurherve commented on profile/README.md
```suggestion
```
One more time ^^

2022-12-19 15:18 UTC, lemeurherve approved these changes

2022-12-20 10:15 UTC, NotMyFault commented
cc @timja or someone else who could merge this PR 👀

2022-12-20 10:20 UTC, merged