Release drafter 5.14 - add autolabeler definition
jenkinsci/.github pull request #46
Opened 2021-03-02 21:10 UTC by warden

Auto-label issues based on branches/titles/body.
https://github.com/release-drafter/release-drafter/releases/tag/v5.14.0

2021-03-03 23:26 UTC, oleg-nenashev requested changes
Looks like one label is wrong

2021-03-03 23:26 UTC, oleg-nenashev commented on .github/release-drafter.yml
> +  - label: 'chore'
```suggestion
  - label: 'documentation'
```

Maybe Asciidoc as well

2021-03-04 09:53 UTC, olblak approved these changes

2021-03-04 13:56 UTC, warden commented on .github/release-drafter.yml
> +  - label: 'chore'
done, asciidoc is not present in the categories at the moment

2021-03-04 15:29 UTC, oleg-nenashev approved these changes
One thing is that conditions are added with "OR", so any match is enough. It means that enhancement pull requests with documentation are likely to set two labels and then lead to two changelog entries. Maybe not the best behavior for the 'files' filter.

CC @jetersen

2021-03-17 09:59 UTC, olblak approved these changes

2021-03-26 09:06 UTC, timja commented
🚢 ?

2021-03-26 09:58 UTC, merged

2021-03-26 09:59 UTC, oleg-nenashev commented
I think we should extend permissions in this repo. Sorry for missing so many pull requests