Add issue form templates
jenkinsci/.github pull request #62
Opened 2021-12-26 08:35 UTC by timja

Inspired by @NotMyFault's port, I did minor changes on top to the bug report to improve formatting of the environment section

see https://github.com/jenkinsci/.github/pull/51#issuecomment-1001070142

Example issus:
https://github.com/timja/.github/issues

Main one being the bug report:
https://github.com/timja/.github/issues/2

2021-12-26 11:08 UTC, NotMyFault requested changes
Otherwise the issue templates looking good as-is

2021-12-26 12:47 UTC, NotMyFault approved these changes

2021-12-27 12:28 UTC, timja commented
@MarkEWaite you able to take a look?

2021-12-27 12:39 UTC, MarkEWaite approved these changes
The change looks great to me.  Does the CI job need to pass before it is merged?

2021-12-27 12:56 UTC, timja commented
> The change looks great to me. Does the CI job need to pass before it is merged?

Just needs a merge with master probably I fixed it separately

2021-12-27 14:21 UTC, merged

2021-12-28 14:36 UTC, jglick commented on .github/ISSUE_TEMPLATE/1-report-bug.yml
> +      required: true
This is now making it impossible to enter a freeform bug report. Can we just have a template _Other_ that gives you a blank space?

2021-12-28 14:40 UTC, jglick commented on .github/ISSUE_TEMPLATE/1-report-bug.yml
> +      required: true
Workaround: file a **Documentation** issue, then clean up the **Description** after filed and correct the labels. https://github.com/jenkinsci/incrementals-tools/issues/21#event-5821597462

2021-12-28 14:42 UTC, NotMyFault commented on .github/ISSUE_TEMPLATE/1-report-bug.yml
> +      required: true
Not _completely_ impossible, the cli does not know about templates 👀 

But I get your point, for quick notifications or follow ups forms may be unnecessary

2021-12-28 15:39 UTC, jglick commented on .github/ISSUE_TEMPLATE/1-report-bug.yml
> +      required: true
The form is nice to guide new contributors who may not be used to thinking in terms of the information a maintainer would need to evaluate something filed out of the blue. It gets in the way for maintainers filing issues for themselves, and experienced contributors with an established working relationship who would already understand what is critical to include in an issue.

2021-12-28 15:44 UTC, NotMyFault commented on .github/ISSUE_TEMPLATE/1-report-bug.yml
> +      required: true
I guess flipping the boolean switch in the config would be sufficient. It doesn't add a separate button for blank issues but the following entry at the bottom of the templates table:
![](https://i.imgur.com/DDd5TxI.png)

2021-12-28 15:49 UTC, timja commented on .github/ISSUE_TEMPLATE/1-report-bug.yml
> +      required: true
continued in https://github.com/jenkinsci/.github/pull/64